export const PRODUCTS = [
  {
    id: "beef-teriyaki-nasi",
    name: "Beef Teriyaki Nasi",
    price: 32000,
    categoryId: "paket-ekonomis",
  },
  {
    id: "beef-yakiniku-nasi",
    name: "Beef Yakiniku Nasi",
    price: 32000,
    categoryId: "paket-ekonomis",
  },
  {
    id: "chicken-teriyaki-nasi",
    name: "Chicken Teriyaki + Nasi",
    price: 28000,
    categoryId: "paket-ekonomis",
  },
  {
    id: "chicken-yakiniku-nasi",
    name: "Chicken Yakiniku Nasi",
    price: 28000,
    categoryId: "paket-ekonomis",
  },
  {
    id: "chicken-katsu",
    name: "Chicken Katsu",
    price: 28000,
    categoryId: "alacarte",
  },
  {
    id: "chicken-gordon-blue",
    name: "Chicken Gordon Blue",
    price: 25000,
    categoryId: "alacarte",
  },
  {
    id: "egg-chicken-roll",
    name: "Egg Chicken Roll",
    price: 24000,
    categoryId: "alacarte",
  },
  {
    id: "ebi-katsu",
    name: "Ebi Katsu",
    price: 27000,
    categoryId: "alacarte",
  },
  {
    id: "ebi-furai",
    name: "Ebi Furai",
    price: 28000,
    categoryId: "alacarte",
  },
  {
    id: "ikkiben-1-new",
    name: "Ikkiben 1 New",
    price: 41000,
    categoryId: "paket-ikkiben-new",
  },
  {
    id: "ikkiben-2-new",
    name: "Ikkiben 2 New",
    price: 41000,
    categoryId: "paket-ikkiben-new",
  },
  {
    id: "ikkiben-3-new",
    name: "Ikkiben 3 New",
    price: 36000,
    categoryId: "paket-ikkiben-new",
  },
  {
    id: "ikkiben-4-new",
    name: "Ikkiben 4 New",
    price: 36000,
    categoryId: "paket-ikkiben-new",
  },
  {
    id: "ikkiben-5-new",
    name: "Ikkiben 5 New",
    price: 38000,
    categoryId: "paket-ikkiben-new",
  },
  {
    id: "ikkiben-6-new",
    name: "Ikkiben 6 New",
    price: 43000,
    categoryId: "paket-ikkiben-new",
  },
  {
    id: "ikkiben-1",
    name: "Ikkiben 1",
    price: 41000,
    categoryId: "paket-ikkiben",
  },
  {
    id: "ikkiben-2",
    name: "Ikkiben 2",
    price: 36000,
    categoryId: "paket-ikkiben",
  },
  {
    id: "ikkiben-3",
    name: "Ikkiben 3",
    price: 41000,
    categoryId: "paket-ikkiben",
  },
  {
    id: "ikkiben-4",
    name: "Ikkiben 4",
    price: 36000,
    categoryId: "paket-ikkiben",
  },
  {
    id: "ikkiben-5",
    name: "Ikkiben 5",
    price: 40000,
    categoryId: "paket-ikkiben",
  },
  {
    id: "ikkiben-6",
    name: "Ikkiben 6",
    price: 43000,
    categoryId: "paket-ikkiben",
  },
  {
    id: "crispy-burger",
    name: "Crispy Burger",
    price: 21000,
    categoryId: "burger",
  },
  {
    id: "crispy-egg-burger",
    name: "Crispy Egg Burger",
    price: 23000,
    categoryId: "burger",
  },
  {
    id: "crispy-cheese-burger",
    name: "Crispy Cheese Burger",
    price: 23000,
    categoryId: "burger",
  },
  {
    id: "crispy-burger-salju",
    name: "Crispy Burger Salju",
    price: 23000,
    categoryId: "burger",
  },
  {
    id: "soft-drink-f-s-c",
    name: "Soft Drink ( F , S , C )",
    price: 6000,
    categoryId: "minuman",
  },
  {
    id: "frestea-jasmine",
    name: "Frestea Jasmine",
    price: 8000,
    categoryId: "minuman",
  },
  {
    id: "aqua-600",
    name: "Aqua 600",
    price: 7000,
    categoryId: "minuman",
  },
  {
    id: "aqua-royal",
    name: "Aqua Royal",
    price: 5000,
    categoryId: "minuman",
  },
  {
    id: "teh-tawar",
    name: "Teh Tawar",
    price: 3000,
    categoryId: "minuman",
  },
  {
    id: "teh-manis",
    name: "Teh Manis",
    price: 6000,
    categoryId: "minuman",
  },
  {
    id: "es-teh-tawar",
    name: "Es Teh Tawar",
    price: 4000,
    categoryId: "minuman",
  },
  {
    id: "es-teh-manis",
    name: "Es Teh Manis",
    price: 7000,
    categoryId: "minuman",
  },
  {
    id: "jeruk-panas",
    name: "Jeruk Panas",
    price: 8000,
    categoryId: "minuman",
  },
  {
    id: "es-jeruk",
    name: "Es Jeruk",
    price: 9000,
    categoryId: "minuman",
  },
  {
    id: "ocha-hot",
    name: "Ocha Hot",
    price: 8000,
    categoryId: "minuman",
  },
  {
    id: "ocha-cold",
    name: "Ocha Cold",
    price: 9000,
    categoryId: "minuman",
  },
  {
    id: "air-putih",
    name: "Air Putih",
    price: 2000,
    categoryId: "minuman",
  },
  {
    id: "es-batu",
    name: "Es Batu",
    price: 2000,
    categoryId: "minuman",
  },
  {
    id: "juice-alpukat",
    name: "Juice Alpukat",
    price: 17000,
    categoryId: "juice",
  },
  {
    id: "juice-jeruk",
    name: "Juice Jeruk",
    price: 15000,
    categoryId: "juice",
  },
  {
    id: "juice-jambu-merah",
    name: "Juice Jambu Merah",
    price: 15000,
    categoryId: "juice",
  },
  {
    id: "juice-cappucino",
    name: "Juice Cappucino",
    price: 15000,
    categoryId: "juice",
  },
  {
    id: "juice-apel",
    name: "Juice Apel",
    price: 15000,
    categoryId: "juice",
  },
  {
    id: "juice-tomat",
    name: "Juice Tomat",
    price: 15000,
    categoryId: "juice",
  },
  {
    id: "juice-strawberry",
    name: "Juice Strawberry",
    price: 17000,
    categoryId: "juice",
  },
  {
    id: "juice-melon",
    name: "Juice Melon",
    price: 16000,
    categoryId: "juice",
  },
  {
    id: "juice-mangga",
    name: "Juice Mangga",
    price: 17000,
    categoryId: "juice",
  },
  {
    id: "juice-wortel",
    name: "Juice Wortel",
    price: 14000,
    categoryId: "juice",
  },
  {
    id: "juice-mix",
    name: "Juice Mix",
    price: 17000,
    categoryId: "juice",
  },
  {
    id: "green-tea-creme",
    name: "Green Tea Creme",
    price: 22000,
    categoryId: "ice-blended",
  },
  {
    id: "taro",
    name: "Taro",
    price: 22000,
    categoryId: "ice-blended",
  },
  {
    id: "chocolate-classic",
    name: "Chocolate Classic",
    price: 22000,
    categoryId: "ice-blended",
  },
  {
    id: "tiramisu",
    name: "Tiramisu",
    price: 22000,
    categoryId: "ice-blended",
  },
  {
    id: "mango-delight",
    name: "Mango Delight",
    price: 22000,
    categoryId: "smoothies",
  },
  {
    id: "kiwi-delight",
    name: "Kiwi Delight",
    price: 22000,
    categoryId: "smoothies",
  },
  {
    id: "blue-hawai-apple",
    name: "Blue Hawai Apple",
    price: 24000,
    categoryId: "mocktail",
  },
  {
    id: "raspberry-apple",
    name: "Raspberry Apple",
    price: 24000,
    categoryId: "mocktail",
  },
  {
    id: "balinest-roll",
    name: "Balinest Roll",
    price: 41000,
    categoryId: "sushi-dong-set",
  },
  {
    id: "kani-tobi-maki",
    name: "Kani Tobi Maki",
    price: 31000,
    categoryId: "sushi-dong-set",
  },
  {
    id: "ikki-resto-fushion",
    name: "Ikki Resto Fushion",
    price: 45000,
    categoryId: "sushi-dong-set",
  },
  {
    id: "gyu-tama-dong-beef",
    name: "Gyu Tama Dong Beef",
    price: 40000,
    categoryId: "sushi-dong-set",
  },
  {
    id: "gyu-tama-dong-chicken",
    name: "Gyu Tama Dong Chicken",
    price: 35000,
    categoryId: "sushi-dong-set",
  },
  {
    id: "salmon-nigiri-tozz",
    name: "Salmon Nigiri Tozz",
    price: 30000,
    categoryId: "sushi-dong-set",
  },
  {
    id: "tamago-nigiri",
    name: "Tamago Nigiri",
    price: 20000,
    categoryId: "sushi-dong-set",
  },
  {
    id: "hand-roll",
    name: "Hand Roll",
    price: 30000,
    categoryId: "sushi-dong-set",
  },
  {
    id: "fujiyama-roll",
    name: "Fujiyama Roll",
    price: 38000,
    categoryId: "sushi-dong-set",
  },
  {
    id: "onigin-chicken",
    name: "Onigin Chicken",
    price: 20000,
    categoryId: "sushi-dong-set",
  },
  {
    id: "onigiri-beef",
    name: "Onigiri Beef",
    price: 25000,
    categoryId: "sushi-dong-set",
  },
  {
    id: "onigin-salmon",
    name: "Onigin Salmon",
    price: 25000,
    categoryId: "sushi-dong-set",
  },
  {
    id: "tobiko-gunkan",
    name: "Tobiko Gunkan",
    price: 35000,
    categoryId: "sushi-dong-set",
  },
  {
    id: "bermuda-triangle",
    name: "Bermuda Triangle",
    price: 35000,
    categoryId: "sushi-dong-set",
  },
  {
    id: "california-roll",
    name: "California Roll",
    price: 34000,
    categoryId: "sushi-dong-set",
  },
  {
    id: "kani-mayo-corn-gunkan",
    name: "Kani Mayo Corn Gunkan",
    price: 20000,
    categoryId: "sushi-dong-set",
  },
  {
    id: "godzilla-roll",
    name: "Godzilla Roll",
    price: 35000,
    categoryId: "sushi-dong-set",
  },
  {
    id: "chicken-katsu-roll-fried-sushi",
    name: "Chicken Katsu Roll",
    price: 22000,
    categoryId: "fried-sushi",
  },
  {
    id: "chicken-teri-roll-fried-sushi",
    name: "Chicken Teri Roll",
    price: 21000,
    categoryId: "fried-sushi",
  },
  {
    id: "kani-mayo-roll-fried-sushi",
    name: "Kani Mayo Roll",
    price: 21000,
    categoryId: "fried-sushi",
  },
  {
    id: "salmon-roll-fried-sushi",
    name: "Salmon Roll",
    price: 26000,
    categoryId: "fried-sushi",
  },
  {
    id: "salmon-teri-roll-fried-sushi",
    name: "Salmon Teri Roll",
    price: 26000,
    categoryId: "fried-sushi",
  },
  {
    id: "kepiting-soka-roll-fried-sushi",
    name: "Kepiting Soka Roll",
    price: 24000,
    categoryId: "fried-sushi",
  },
  {
    id: "bulgogi-roll-fried-sushi",
    name: "Bulgogi Roll",
    price: 25000,
    categoryId: "fried-sushi",
  },
  {
    id: "mie-chicken-teriyaki-aneka-mie",
    name: "Mie Chicken Teriyaki",
    price: 27000,
    categoryId: "aneka-mie",
  },
  {
    id: "mie-beef-teriyaki-aneka-mie",
    name: "Mie Beef Teriyaki",
    price: 30000,
    categoryId: "aneka-mie",
  },
  {
    id: "mie-chicken-yakiniku-aneka-mie",
    name: "Mie Chicken Yakiniku",
    price: 27000,
    categoryId: "aneka-mie",
  },
  {
    id: "mie-beef-yakiniku-aneka-mie",
    name: "Mie Beef Yakiniku",
    price: 30000,
    categoryId: "aneka-mie",
  },
  {
    id: "mie-ayam-aneka-mie",
    name: "Mie Ayam",
    price: 25000,
    categoryId: "aneka-mie",
  },
  {
    id: "mie-crispy-yakiniku-aneka-mie",
    name: "Mie Crispy Yakiniku",
    price: 29000,
    categoryId: "aneka-mie",
  },
  {
    id: "chicken-yakisoba-aneka-mie",
    name: "Chicken Yakisoba",
    price: 30000,
    categoryId: "aneka-mie",
  },
  {
    id: "beef-yakisoba-aneka-mie",
    name: "Beef Yakisoba",
    price: 34000,
    categoryId: "aneka-mie",
  },
  {
    id: "chicken-steak-barbeque-hot-plate",
    name: "Chicken Steak Barbeque",
    price: 34000,
    categoryId: "hot-plate",
  },
  {
    id: "chicken-steak-asam-manis-hot-plate",
    name: "Chicken Steak Asam Manis",
    price: 34000,
    categoryId: "hot-plate",
  },
  {
    id: "chicken-steak-teriyaki-hot-plate",
    name: "Chicken Steak Teriyaki",
    price: 34000,
    categoryId: "hot-plate",
  },
  {
    id: "yakimeshi-crispy-hot-plate",
    name: "Yakimeshi Crispy",
    price: 34000,
    categoryId: "hot-plate",
  },
  {
    id: "mie-hot-plate-barbeque-hot-plate",
    name: "Mie Hot Plate Barbeque",
    price: 34000,
    categoryId: "hot-plate",
  },
  {
    id: "mie-hot-plate-teriyaki-hot-plate",
    name: "Mie Hot Plate Teriyaki",
    price: 34000,
    categoryId: "hot-plate",
  },
  {
    id: "nasi-putih-lain-lain",
    name: "Nasi Putih",
    price: 6000,
    categoryId: "lain-lain",
  },
  {
    id: "yakimeshi-lain-lain",
    name: "Yakimeshi",
    price: 23000,
    categoryId: "lain-lain",
  },
  {
    id: "french-fries-lain-lain",
    name: "French Fries",
    price: 17000,
    categoryId: "lain-lain",
  },
  {
    id: "tornado-twist-lain-lain",
    name: "Tornado Twist",
    price: 31000,
    categoryId: "lain-lain",
  },
  {
    id: "curry-chicken-nasi-lain-lain",
    name: "Curry Chicken Nasi",
    price: 33000,
    categoryId: "lain-lain",
  },
  {
    id: "curry-ebi-katsu-nasi-lain-lain",
    name: "Curry Ebi Katsu Nasi",
    price: 37000,
    categoryId: "lain-lain",
  },
  {
    id: "curry-ebi-furai-nasi-lain-lain",
    name: "Curry Ebi Furai Nasi",
    price: 37000,
    categoryId: "lain-lain",
  },
  {
    id: "curry-spicy-chicken-nasi-lain-lain",
    name: "Curry Spicy Chicken Nasi",
    price: 35000,
    categoryId: "lain-lain",
  },
  {
    id: "curry-shrimp-roll-nasi-lain-lain",
    name: "Curry Shrimp Roll + Nasi",
    price: 35000,
    categoryId: "lain-lain",
  },
  {
    id: "curry-chicken-katsu-nasi-lain-lain",
    name: "Curry Chicken Katsu Nasi",
    price: 35000,
    categoryId: "lain-lain",
  },
  {
    id: "sapi-lada-hitam-nasi-lain-lain",
    name: "Sapi Lada Hitam + Nasi",
    price: 39000,
    categoryId: "lain-lain",
  },
  {
    id: "ayam-lada-hitam-nasi-lain-lain",
    name: "Ayam Lada Hitam + Nasi",
    price: 35000,
    categoryId: "lain-lain",
  },
  {
    id: "salad-lain-lain",
    name: "Salad",
    price: 12000,
    categoryId: "lain-lain",
  },
  {
    id: "kuah-gyu-tama-dong-lain-lain",
    name: "Kuah Gyu Tama Dong",
    price: 6000,
    categoryId: "lain-lain",
  },
  {
    id: "mayonaise-lain-lain",
    name: "Mayonaise",
    price: 7000,
    categoryId: "lain-lain",
  },
  {
    id: "telur-lain-lain",
    name: "Telur",
    price: 7000,
    categoryId: "lain-lain",
  },
  {
    id: "tobiko-telur-ikan-lain-lain",
    name: "Tobiko (Telur Ikan)",
    price: 20000,
    categoryId: "lain-lain",
  },
  {
    id: "tamago-dadar-gulung-lain-lain",
    name: "Tamago (Dadar Gulung)",
    price: 12000,
    categoryId: "lain-lain",
  },
  {
    id: "pangsit-lain-lain",
    name: "Pangsit",
    price: 2000,
    categoryId: "lain-lain",
  },
  {
    id: "keju-lain-lain",
    name: "Keju",
    price: 5000,
    categoryId: "lain-lain",
  },
  {
    id: "siomay-dimsum-isi-4",
    name: "Siomay",
    price: 21000,
    categoryId: "dimsum-isi-4",
  },
  {
    id: "swekiau-dimsum-isi-4",
    name: "Swekiau",
    price: 21000,
    categoryId: "dimsum-isi-4",
  },
  {
    id: "lumpia-kulit-tahu-dimsum-isi-4",
    name: "Lumpia Kulit Tahu",
    price: 21000,
    categoryId: "dimsum-isi-4",
  },
  {
    id: "chicken-ramen",
    name: "Chicken Ramen",
    price: 31000,
    categoryId: "ramen",
  },
  {
    id: "beef-ramen",
    name: "Beef Ramen",
    price: 35000,
    categoryId: "ramen",
  },
  {
    id: "chicken-udon",
    name: "Chicken Udon",
    price: 32000,
    categoryId: "udon",
  },
  {
    id: "beef-udon",
    name: "Beef Udon",
    price: 36000,
    categoryId: "udon",
  },
]

export const CATEGORIES = [
  { id: "all", name: "Semua" },
  { id: "paket-ekonomis", name: "Paket Ekonomis" },
  { id: "alacarte", name: "Alacarte" },
  { id: "paket-ikkiben-new", name: "Paket IKKIBEN NEW" },
  { id: "paket-ikkiben", name: "Paket IKKIBEN" },
  { id: "burger", name: "Burger" },
  { id: "minuman", name: "Minuman" },
  { id: "juice", name: "Juice" },
  { id: "ice-blended", name: "Ice Blended" },
  { id: "smoothies", name: "Smoothies" },
  { id: "mocktail", name: "Mocktail" },
  { id: "sushi-dong-set", name: "Sushi & Dong Set" },
  { id: "fried-sushi", name: "Fried Sushi" },
  { id: "aneka-mie", name: "Aneka Mie" },
  { id: "hot-plate", name: "Hot Plate" },
  { id: "lain-lain", name: "Lain - lain" },
  { id: "dimsum-isi-4", name: "Dimsum (isi 4)" },
  { id: "ramen", name: "Ramen" },
  { id: "udon", name: "Udon" },
]
